<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => '1',
                'data_type_id' => '1',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '1',
            ),
            1 => 
            array (
                'id' => '2',
                'data_type_id' => '1',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '2',
            ),
            2 => 
            array (
                'id' => '3',
                'data_type_id' => '1',
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '3',
            ),
            3 => 
            array (
                'id' => '4',
                'data_type_id' => '1',
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Password',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => NULL,
                'order' => '4',
            ),
            4 => 
            array (
                'id' => '5',
                'data_type_id' => '1',
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '5',
            ),
            5 => 
            array (
                'id' => '6',
                'data_type_id' => '1',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '6',
            ),
            6 => 
            array (
                'id' => '7',
                'data_type_id' => '1',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '7',
            ),
            7 => 
            array (
                'id' => '8',
                'data_type_id' => '1',
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '8',
            ),
            8 => 
            array (
                'id' => '9',
                'data_type_id' => '1',
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":0}',
                'order' => '10',
            ),
            9 => 
            array (
                'id' => '10',
                'data_type_id' => '1',
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Roles',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order' => '11',
            ),
            10 => 
            array (
                'id' => '11',
                'data_type_id' => '1',
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '12',
            ),
            11 => 
            array (
                'id' => '12',
                'data_type_id' => '2',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '1',
            ),
            12 => 
            array (
                'id' => '13',
                'data_type_id' => '2',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '2',
            ),
            13 => 
            array (
                'id' => '14',
                'data_type_id' => '2',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '3',
            ),
            14 => 
            array (
                'id' => '15',
                'data_type_id' => '2',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '4',
            ),
            15 => 
            array (
                'id' => '16',
                'data_type_id' => '3',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '1',
            ),
            16 => 
            array (
                'id' => '17',
                'data_type_id' => '3',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '2',
            ),
            17 => 
            array (
                'id' => '18',
                'data_type_id' => '3',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '3',
            ),
            18 => 
            array (
                'id' => '19',
                'data_type_id' => '3',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '4',
            ),
            19 => 
            array (
                'id' => '20',
                'data_type_id' => '3',
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '5',
            ),
            20 => 
            array (
                'id' => '21',
                'data_type_id' => '1',
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '9',
            ),
            21 => 
            array (
                'id' => '22',
                'data_type_id' => '4',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '1',
            ),
            22 => 
            array (
                'id' => '23',
                'data_type_id' => '4',
                'field' => 'parent_id',
                'type' => 'select_dropdown',
                'display_name' => 'Parent',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"default":"","null":"","options":{"":"-- None --"},"relationship":{"key":"id","label":"name"}}',
                'order' => '2',
            ),
            23 => 
            array (
                'id' => '24',
                'data_type_id' => '4',
                'field' => 'order',
                'type' => 'text',
                'display_name' => 'Order',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"default":1}',
                'order' => '3',
            ),
            24 => 
            array (
                'id' => '25',
                'data_type_id' => '4',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '4',
            ),
            25 => 
            array (
                'id' => '26',
                'data_type_id' => '4',
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"slugify":{"origin":"name"}}',
                'order' => '5',
            ),
            26 => 
            array (
                'id' => '27',
                'data_type_id' => '4',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '6',
            ),
            27 => 
            array (
                'id' => '28',
                'data_type_id' => '4',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '7',
            ),
            28 => 
            array (
                'id' => '29',
                'data_type_id' => '5',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '1',
            ),
            29 => 
            array (
                'id' => '30',
                'data_type_id' => '5',
                'field' => 'author_id',
                'type' => 'text',
                'display_name' => 'Author',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => NULL,
                'order' => '2',
            ),
            30 => 
            array (
                'id' => '31',
                'data_type_id' => '5',
                'field' => 'category_id',
                'type' => 'text',
                'display_name' => 'Category',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => NULL,
                'order' => '3',
            ),
            31 => 
            array (
                'id' => '32',
                'data_type_id' => '5',
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '4',
            ),
            32 => 
            array (
                'id' => '33',
                'data_type_id' => '5',
                'field' => 'excerpt',
                'type' => 'text_area',
                'display_name' => 'Excerpt',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '5',
            ),
            33 => 
            array (
                'id' => '34',
                'data_type_id' => '5',
                'field' => 'body',
                'type' => 'rich_text_box',
                'display_name' => 'Body',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '6',
            ),
            34 => 
            array (
                'id' => '35',
                'data_type_id' => '5',
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Post Image',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"resize":{"width":"1000","height":"null"},"quality":"70%","upsize":true,"thumbnails":[{"name":"medium","scale":"50%"},{"name":"small","scale":"25%"},{"name":"cropped","crop":{"width":"300","height":"250"}}]}',
                'order' => '7',
            ),
            35 => 
            array (
                'id' => '36',
                'data_type_id' => '5',
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"slugify":{"origin":"title","forceUpdate":true},"validation":{"rule":"unique:posts,slug"}}',
                'order' => '8',
            ),
            36 => 
            array (
                'id' => '37',
                'data_type_id' => '5',
                'field' => 'meta_description',
                'type' => 'text_area',
                'display_name' => 'Meta Description',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '9',
            ),
            37 => 
            array (
                'id' => '38',
                'data_type_id' => '5',
                'field' => 'meta_keywords',
                'type' => 'text_area',
                'display_name' => 'Meta Keywords',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '10',
            ),
            38 => 
            array (
                'id' => '39',
                'data_type_id' => '5',
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Status',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"default":"DRAFT","options":{"PUBLISHED":"published","DRAFT":"draft","PENDING":"pending"}}',
                'order' => '11',
            ),
            39 => 
            array (
                'id' => '40',
                'data_type_id' => '5',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '12',
            ),
            40 => 
            array (
                'id' => '41',
                'data_type_id' => '5',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '13',
            ),
            41 => 
            array (
                'id' => '42',
                'data_type_id' => '5',
                'field' => 'seo_title',
                'type' => 'text',
                'display_name' => 'SEO Title',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '14',
            ),
            42 => 
            array (
                'id' => '43',
                'data_type_id' => '5',
                'field' => 'featured',
                'type' => 'checkbox',
                'display_name' => 'Featured',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '15',
            ),
            43 => 
            array (
                'id' => '44',
                'data_type_id' => '6',
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '1',
            ),
            44 => 
            array (
                'id' => '45',
                'data_type_id' => '6',
                'field' => 'author_id',
                'type' => 'text',
                'display_name' => 'Author',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '2',
            ),
            45 => 
            array (
                'id' => '46',
                'data_type_id' => '6',
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '3',
            ),
            46 => 
            array (
                'id' => '47',
                'data_type_id' => '6',
                'field' => 'excerpt',
                'type' => 'text_area',
                'display_name' => 'Excerpt',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '4',
            ),
            47 => 
            array (
                'id' => '48',
                'data_type_id' => '6',
                'field' => 'body',
                'type' => 'rich_text_box',
                'display_name' => 'Body',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '5',
            ),
            48 => 
            array (
                'id' => '49',
                'data_type_id' => '6',
                'field' => 'slug',
                'type' => 'text',
                'display_name' => 'Slug',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"slugify":{"origin":"title"},"validation":{"rule":"unique:pages,slug"}}',
                'order' => '6',
            ),
            49 => 
            array (
                'id' => '50',
                'data_type_id' => '6',
                'field' => 'meta_description',
                'type' => 'text',
                'display_name' => 'Meta Description',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '7',
            ),
            50 => 
            array (
                'id' => '51',
                'data_type_id' => '6',
                'field' => 'meta_keywords',
                'type' => 'text',
                'display_name' => 'Meta Keywords',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '8',
            ),
            51 => 
            array (
                'id' => '52',
                'data_type_id' => '6',
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Status',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"default":"INACTIVE","options":{"INACTIVE":"INACTIVE","ACTIVE":"ACTIVE"}}',
                'order' => '9',
            ),
            52 => 
            array (
                'id' => '53',
                'data_type_id' => '6',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '10',
            ),
            53 => 
            array (
                'id' => '54',
                'data_type_id' => '6',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => NULL,
                'order' => '11',
            ),
            54 => 
            array (
                'id' => '55',
                'data_type_id' => '6',
                'field' => 'image',
                'type' => 'image',
                'display_name' => 'Page Image',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => NULL,
                'order' => '12',
            ),
            55 => 
            array (
                'id' => '101',
                'data_type_id' => '10',
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '1',
            ),
            56 => 
            array (
                'id' => '102',
                'data_type_id' => '10',
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => '{}',
                'order' => '5',
            ),
            57 => 
            array (
                'id' => '103',
                'data_type_id' => '10',
                'field' => 'description',
                'type' => 'rich_text_box',
                'display_name' => 'Description',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => '{}',
                'order' => '17',
            ),
            58 => 
            array (
                'id' => '104',
                'data_type_id' => '10',
                'field' => 'price',
                'type' => 'text',
                'display_name' => 'Price',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => '{}',
                'order' => '13',
            ),
            59 => 
            array (
                'id' => '105',
                'data_type_id' => '10',
                'field' => 'fees',
                'type' => 'text',
                'display_name' => 'Fees',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => '{}',
                'order' => '15',
            ),
            60 => 
            array (
                'id' => '106',
                'data_type_id' => '10',
                'field' => 'p_method',
                'type' => 'hidden',
                'display_name' => 'P Method',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '21',
            ),
            61 => 
            array (
                'id' => '107',
                'data_type_id' => '10',
                'field' => 'currency',
                'type' => 'hidden',
                'display_name' => 'Currency',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '22',
            ),
            62 => 
            array (
                'id' => '108',
                'data_type_id' => '10',
                'field' => 'pm_slug',
                'type' => 'hidden',
                'display_name' => 'Pm Slug',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '10',
            ),
            63 => 
            array (
                'id' => '109',
                'data_type_id' => '10',
                'field' => 'duration',
                'type' => 'select_dropdown',
                'display_name' => 'Duration',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => '{"options":{"0":"---------","1":"30 - 60 Minutes","2":"01 - 06 Houres","3":"06 - 12 Houres","4":"12 - 24 Houres","5":"01 - 03 Days","6":"03 - 06 Days","7":"06 - 12 Days","8":"12 - 24 Days","9":"24 - 48 Days","10":"01 - 03 Months","11":"03 - 06 Months","12":"06 - 12 Months"}}',
                'order' => '16',
            ),
            64 => 
            array (
                'id' => '110',
                'data_type_id' => '10',
                'field' => 'purchases_number',
                'type' => 'number',
                'display_name' => 'Purchases Number',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '3',
            ),
            65 => 
            array (
                'id' => '111',
                'data_type_id' => '10',
                'field' => 'remaining',
                'type' => 'number',
                'display_name' => 'Quantity',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => '{}',
                'order' => '14',
            ),
            66 => 
            array (
                'id' => '112',
                'data_type_id' => '10',
                'field' => 'img_path',
                'type' => 'image',
                'display_name' => 'Img Path',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '0',
                'details' => '{}',
                'order' => '18',
            ),
            67 => 
            array (
                'id' => '113',
                'data_type_id' => '10',
                'field' => 'the_status',
                'type' => 'select_dropdown',
                'display_name' => 'The Status',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '0',
                'details' => '{"default":"open","options":{"open":"open","closed":"closed","pending":"pending"}}',
                'order' => '2',
            ),
            68 => 
            array (
                'id' => '114',
                'data_type_id' => '10',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '19',
            ),
            69 => 
            array (
                'id' => '115',
                'data_type_id' => '10',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '20',
            ),
            70 => 
            array (
                'id' => '126',
                'data_type_id' => '13',
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '1',
            ),
            71 => 
            array (
                'id' => '127',
                'data_type_id' => '13',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '2',
            ),
            72 => 
            array (
                'id' => '128',
                'data_type_id' => '13',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '3',
            ),
            73 => 
            array (
                'id' => '129',
                'data_type_id' => '13',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '4',
            ),
            74 => 
            array (
                'id' => '130',
                'data_type_id' => '14',
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '1',
            ),
            75 => 
            array (
                'id' => '131',
                'data_type_id' => '14',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '2',
            ),
            76 => 
            array (
                'id' => '132',
                'data_type_id' => '14',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '3',
            ),
            77 => 
            array (
                'id' => '133',
                'data_type_id' => '14',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '4',
            ),
            78 => 
            array (
                'id' => '134',
                'data_type_id' => '10',
                'field' => 'service_belongsto_payment_method_relationship_1',
                'type' => 'relationship',
                'display_name' => 'p_method',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"model":"App\\\\PaymentMethod","table":"payment_methods","type":"belongsTo","column":"p_method","key":"name","label":"name","pivot_table":"balances","pivot":"0","taggable":"0"}',
                'order' => '11',
            ),
            79 => 
            array (
                'id' => '135',
                'data_type_id' => '10',
                'field' => 'service_belongsto_currency_relationship',
                'type' => 'relationship',
                'display_name' => 'currency',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"model":"App\\\\Currency","table":"currencies","type":"belongsTo","column":"currency","key":"name","label":"name","pivot_table":"balances","pivot":"0","taggable":"0"}',
                'order' => '12',
            ),
            80 => 
            array (
                'id' => '137',
                'data_type_id' => '15',
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '1',
            ),
            81 => 
            array (
                'id' => '138',
                'data_type_id' => '15',
                'field' => 'user_id',
                'type' => 'text',
                'display_name' => 'User Id',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '2',
            ),
            82 => 
            array (
                'id' => '139',
                'data_type_id' => '15',
                'field' => 'service_id',
                'type' => 'text',
                'display_name' => 'Service Id',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '3',
            ),
            83 => 
            array (
                'id' => '140',
                'data_type_id' => '15',
                'field' => 'payment_id',
                'type' => 'text',
                'display_name' => 'Payment Id',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '4',
            ),
            84 => 
            array (
                'id' => '141',
                'data_type_id' => '15',
                'field' => 'the_status',
                'type' => 'text',
                'display_name' => 'The Status',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '5',
            ),
            85 => 
            array (
                'id' => '142',
                'data_type_id' => '15',
                'field' => 'notes',
                'type' => 'text',
                'display_name' => 'Notes',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '6',
            ),
            86 => 
            array (
                'id' => '143',
                'data_type_id' => '15',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '7',
            ),
            87 => 
            array (
                'id' => '144',
                'data_type_id' => '15',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '8',
            ),
            88 => 
            array (
                'id' => '158',
                'data_type_id' => '17',
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '1',
            ),
            89 => 
            array (
                'id' => '159',
                'data_type_id' => '17',
                'field' => 'user_id',
                'type' => 'hidden',
                'display_name' => 'User Id',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '3',
            ),
            90 => 
            array (
                'id' => '160',
                'data_type_id' => '17',
                'field' => 'service_id',
                'type' => 'hidden',
                'display_name' => 'Service Id',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '5',
            ),
            91 => 
            array (
                'id' => '161',
                'data_type_id' => '17',
                'field' => 'quantity',
                'type' => 'text',
                'display_name' => 'Quantity',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '8',
            ),
            92 => 
            array (
                'id' => '162',
                'data_type_id' => '17',
                'field' => 'payment_method',
                'type' => 'text',
                'display_name' => 'Payment Method',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '9',
            ),
            93 => 
            array (
                'id' => '163',
                'data_type_id' => '17',
                'field' => 'price',
                'type' => 'text',
                'display_name' => 'Price',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '10',
            ),
            94 => 
            array (
                'id' => '164',
                'data_type_id' => '17',
                'field' => 'fees',
                'type' => 'text',
                'display_name' => 'Fees',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '11',
            ),
            95 => 
            array (
                'id' => '165',
                'data_type_id' => '17',
                'field' => 'total',
                'type' => 'text',
                'display_name' => 'Total',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '12',
            ),
            96 => 
            array (
                'id' => '166',
                'data_type_id' => '17',
                'field' => 'current_balance',
                'type' => 'text',
                'display_name' => 'Current Balance',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '13',
            ),
            97 => 
            array (
                'id' => '167',
                'data_type_id' => '17',
                'field' => 'new_balance',
                'type' => 'text',
                'display_name' => 'New Balance',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '14',
            ),
            98 => 
            array (
                'id' => '168',
                'data_type_id' => '17',
                'field' => 'the_status',
                'type' => 'text',
                'display_name' => 'The Status',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '15',
            ),
            99 => 
            array (
                'id' => '169',
                'data_type_id' => '17',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '16',
            ),
            100 => 
            array (
                'id' => '170',
                'data_type_id' => '17',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '17',
            ),
            101 => 
            array (
                'id' => '171',
                'data_type_id' => '17',
                'field' => 'conversation_id',
                'type' => 'hidden',
                'display_name' => 'Conversation Id',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '7',
            ),
            102 => 
            array (
                'id' => '172',
                'data_type_id' => '17',
                'field' => 'payment_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'users',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '0',
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"name","pivot_table":"balances","pivot":"0","taggable":"0"}',
                'order' => '2',
            ),
            103 => 
            array (
                'id' => '173',
                'data_type_id' => '17',
                'field' => 'payment_belongsto_service_relationship',
                'type' => 'relationship',
                'display_name' => 'services',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '0',
                'details' => '{"model":"App\\\\Service","table":"services","type":"belongsTo","column":"service_id","key":"id","label":"title","pivot_table":"balances","pivot":"0","taggable":"0"}',
                'order' => '4',
            ),
            104 => 
            array (
                'id' => '174',
                'data_type_id' => '17',
                'field' => 'payment_belongsto_conversation_relationship',
                'type' => 'relationship',
                'display_name' => 'conversations',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{"model":"App\\\\Conversation","table":"conversations","type":"belongsTo","column":"conversation_id","key":"id","label":"id","pivot_table":"balances","pivot":"0","taggable":"0"}',
                'order' => '6',
            ),
            105 => 
            array (
                'id' => '175',
                'data_type_id' => '18',
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '1',
            ),
            106 => 
            array (
                'id' => '176',
                'data_type_id' => '18',
                'field' => 'user_id',
                'type' => 'hidden',
                'display_name' => 'User Id',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '5',
            ),
            107 => 
            array (
                'id' => '178',
                'data_type_id' => '18',
                'field' => 'amount',
                'type' => 'number',
                'display_name' => 'Amount',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '7',
            ),
            108 => 
            array (
                'id' => '179',
                'data_type_id' => '18',
                'field' => 'send_date',
                'type' => 'timestamp',
                'display_name' => 'Send Date',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '8',
            ),
            109 => 
            array (
                'id' => '180',
                'data_type_id' => '18',
                'field' => 'img_path',
                'type' => 'image',
                'display_name' => 'Img Path',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '2',
            ),
            110 => 
            array (
                'id' => '181',
                'data_type_id' => '18',
                'field' => 'the_status',
                'type' => 'select_dropdown',
                'display_name' => 'The Status',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"default":"Open","options":{"Accepted":"Accepted","Open":"Open","Refused":"Refused"}}',
                'order' => '12',
            ),
            111 => 
            array (
                'id' => '182',
                'data_type_id' => '18',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '9',
            ),
            112 => 
            array (
                'id' => '183',
                'data_type_id' => '18',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '10',
            ),
            113 => 
            array (
                'id' => '184',
                'data_type_id' => '18',
                'field' => 'deposit_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'users',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"name","pivot_table":"balances","pivot":"0","taggable":"0"}',
                'order' => '3',
            ),
            114 => 
            array (
                'id' => '186',
                'data_type_id' => '18',
                'field' => 'p_method',
                'type' => 'text',
                'display_name' => 'P Method',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '4',
            ),
            115 => 
            array (
                'id' => '187',
                'data_type_id' => '18',
                'field' => 'currency',
                'type' => 'text',
                'display_name' => 'Currency',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '6',
            ),
            116 => 
            array (
                'id' => '188',
                'data_type_id' => '18',
                'field' => 'the_queue',
                'type' => 'text',
                'display_name' => 'The Queue',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '11',
            ),
            117 => 
            array (
                'id' => '189',
                'data_type_id' => '19',
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '1',
            ),
            118 => 
            array (
                'id' => '190',
                'data_type_id' => '19',
                'field' => 'user_id',
                'type' => 'hidden',
                'display_name' => 'User Id',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '4',
            ),
            119 => 
            array (
                'id' => '191',
                'data_type_id' => '19',
                'field' => 'p_method',
                'type' => 'hidden',
                'display_name' => 'P Method',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '6',
            ),
            120 => 
            array (
                'id' => '192',
                'data_type_id' => '19',
                'field' => 'currency',
                'type' => 'hidden',
                'display_name' => 'Currency',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '8',
            ),
            121 => 
            array (
                'id' => '193',
                'data_type_id' => '19',
                'field' => 'amount',
                'type' => 'number',
                'display_name' => 'Amount',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '9',
            ),
            122 => 
            array (
                'id' => '194',
                'data_type_id' => '19',
                'field' => 'the_queue',
                'type' => 'number',
                'display_name' => 'The Queue',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '2',
            ),
            123 => 
            array (
                'id' => '195',
                'data_type_id' => '19',
                'field' => 'the_status',
                'type' => 'text',
                'display_name' => 'The Status',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '10',
            ),
            124 => 
            array (
                'id' => '196',
                'data_type_id' => '19',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '11',
            ),
            125 => 
            array (
                'id' => '197',
                'data_type_id' => '19',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '12',
            ),
            126 => 
            array (
                'id' => '198',
                'data_type_id' => '19',
                'field' => 'withdraw_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'users',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"user_id","key":"id","label":"name","pivot_table":"activity_log","pivot":"0","taggable":"0"}',
                'order' => '3',
            ),
            127 => 
            array (
                'id' => '199',
                'data_type_id' => '19',
                'field' => 'withdraw_belongsto_payment_method_relationship',
                'type' => 'relationship',
                'display_name' => 'payment_methods',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"model":"App\\\\PaymentMethod","table":"payment_methods","type":"belongsTo","column":"p_method","key":"name","label":"name","pivot_table":"activity_log","pivot":"0","taggable":"0"}',
                'order' => '5',
            ),
            128 => 
            array (
                'id' => '200',
                'data_type_id' => '19',
                'field' => 'withdraw_belongsto_currency_relationship',
                'type' => 'relationship',
                'display_name' => 'currencies',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"model":"App\\\\Currency","table":"currencies","type":"belongsTo","column":"currency","key":"name","label":"name","pivot_table":"activity_log","pivot":"0","taggable":"0"}',
                'order' => '7',
            ),
            129 => 
            array (
                'id' => '205',
                'data_type_id' => '22',
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '1',
            ),
            130 => 
            array (
                'id' => '206',
                'data_type_id' => '22',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '2',
            ),
            131 => 
            array (
                'id' => '207',
                'data_type_id' => '22',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '3',
            ),
            132 => 
            array (
                'id' => '208',
                'data_type_id' => '22',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '4',
            ),
            133 => 
            array (
                'id' => '209',
                'data_type_id' => '22',
                'field' => 'slug_name',
                'type' => 'text',
                'display_name' => 'Slug Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '3',
            ),
            134 => 
            array (
                'id' => '210',
                'data_type_id' => '23',
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '1',
            ),
            135 => 
            array (
                'id' => '211',
                'data_type_id' => '23',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '4',
            ),
            136 => 
            array (
                'id' => '212',
                'data_type_id' => '23',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '5',
            ),
            137 => 
            array (
                'id' => '213',
                'data_type_id' => '23',
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '2',
            ),
            138 => 
            array (
                'id' => '214',
                'data_type_id' => '23',
                'field' => 'slug_name',
                'type' => 'text',
                'display_name' => 'Slug Name',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '3',
            ),
            139 => 
            array (
                'id' => '215',
                'data_type_id' => '10',
                'field' => 'service_belongsto_service_category_relationship',
                'type' => 'relationship',
                'display_name' => 'service_categories',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"model":"App\\\\ServiceCategory","table":"service_categories","type":"belongsTo","column":"category","key":"slug_name","label":"name","pivot_table":"activity_log","pivot":"0","taggable":"0"}',
                'order' => '6',
            ),
            140 => 
            array (
                'id' => '216',
                'data_type_id' => '10',
                'field' => 'service_belongsto_service_sub_category_relationship',
                'type' => 'relationship',
                'display_name' => 'service_sub_categories',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{"model":"App\\\\ServiceSubCategory","table":"service_sub_categories","type":"belongsTo","column":"sub_category","key":"slug_name","label":"name","pivot_table":"activity_log","pivot":"0","taggable":"0"}',
                'order' => '8',
            ),
            141 => 
            array (
                'id' => '217',
                'data_type_id' => '10',
                'field' => 'category',
                'type' => 'text',
                'display_name' => 'Category',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '7',
            ),
            142 => 
            array (
                'id' => '218',
                'data_type_id' => '10',
                'field' => 'sub_category',
                'type' => 'text',
                'display_name' => 'Sub Category',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '9',
            ),
            143 => 
            array (
                'id' => '219',
                'data_type_id' => '17',
                'field' => 'currency',
                'type' => 'text',
                'display_name' => 'Currency',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '7',
            ),
            144 => 
            array (
                'id' => '221',
                'data_type_id' => '10',
                'field' => 'creator_id',
                'type' => 'hidden',
                'display_name' => 'Creator Id',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '4',
            ),
            145 => 
            array (
                'id' => '222',
                'data_type_id' => '24',
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '1',
            ),
            146 => 
            array (
                'id' => '223',
                'data_type_id' => '24',
                'field' => 'url',
                'type' => 'text',
                'display_name' => 'Url',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '2',
            ),
            147 => 
            array (
                'id' => '224',
                'data_type_id' => '24',
                'field' => 'title',
                'type' => 'text',
                'display_name' => 'Title',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '3',
            ),
            148 => 
            array (
                'id' => '225',
                'data_type_id' => '24',
                'field' => 'content',
                'type' => 'rich_text_box',
                'display_name' => 'Content',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '4',
            ),
            149 => 
            array (
                'id' => '226',
                'data_type_id' => '24',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '5',
            ),
            150 => 
            array (
                'id' => '227',
                'data_type_id' => '24',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '0',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '6',
            ),
            151 => 
            array (
                'id' => '228',
                'data_type_id' => '13',
                'field' => 'the_sign',
                'type' => 'text',
                'display_name' => 'The Sign',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '3',
            ),
            152 => 
            array (
                'id' => '229',
                'data_type_id' => '13',
                'field' => 'compatible_with',
                'type' => 'text',
                'display_name' => 'Compatible With',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '4',
            ),
            153 => 
            array (
                'id' => '230',
                'data_type_id' => '18',
                'field' => 'p_info',
                'type' => 'text',
                'display_name' => 'P Info',
                'required' => '0',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '1',
                'delete' => '0',
                'details' => '{}',
                'order' => '3',
            ),
            154 => 
            array (
                'id' => '231',
                'data_type_id' => '18',
                'field' => 'urgent_verification',
                'type' => 'text',
                'display_name' => 'Urgent Verification',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '10',
            ),
            155 => 
            array (
                'id' => '232',
                'data_type_id' => '10',
                'field' => 'num_raters',
                'type' => 'text',
                'display_name' => 'Num Raters',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '16',
            ),
            156 => 
            array (
                'id' => '233',
                'data_type_id' => '10',
                'field' => 'num_stars',
                'type' => 'text',
                'display_name' => 'Num Stars',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '1',
                'add' => '1',
                'delete' => '1',
                'details' => '{}',
                'order' => '17',
            ),
            157 => 
            array (
                'id' => '234',
                'data_type_id' => '10',
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => '0',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '1',
                'details' => '{}',
                'order' => '21',
            ),
            158 => 
            array (
                'id' => '235',
                'data_type_id' => '25',
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => '1',
                'browse' => '0',
                'read' => '0',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '1',
            ),
            159 => 
            array (
                'id' => '236',
                'data_type_id' => '25',
                'field' => 'user_id',
                'type' => 'text',
                'display_name' => 'User Id',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '2',
            ),
            160 => 
            array (
                'id' => '237',
                'data_type_id' => '25',
                'field' => 'ccp_dinar',
                'type' => 'text',
                'display_name' => 'Ccp Dinar',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '3',
            ),
            161 => 
            array (
                'id' => '238',
                'data_type_id' => '25',
                'field' => 'paypal_usd',
                'type' => 'text',
                'display_name' => 'Paypal Usd',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '4',
            ),
            162 => 
            array (
                'id' => '239',
                'data_type_id' => '25',
                'field' => 'paypal_euro',
                'type' => 'text',
                'display_name' => 'Paypal Euro',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '5',
            ),
            163 => 
            array (
                'id' => '240',
                'data_type_id' => '25',
                'field' => 'paysera_usd',
                'type' => 'text',
                'display_name' => 'Paysera Usd',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '6',
            ),
            164 => 
            array (
                'id' => '241',
                'data_type_id' => '25',
                'field' => 'paysera_euro',
                'type' => 'text',
                'display_name' => 'Paysera Euro',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '7',
            ),
            165 => 
            array (
                'id' => '242',
                'data_type_id' => '25',
                'field' => 'mobilis_dinar',
                'type' => 'text',
                'display_name' => 'Mobilis Dinar',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '8',
            ),
            166 => 
            array (
                'id' => '243',
                'data_type_id' => '25',
                'field' => 'ooredoo_dinar',
                'type' => 'text',
                'display_name' => 'Ooredoo Dinar',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '9',
            ),
            167 => 
            array (
                'id' => '244',
                'data_type_id' => '25',
                'field' => 'djezzy_dinar',
                'type' => 'text',
                'display_name' => 'Djezzy Dinar',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '10',
            ),
            168 => 
            array (
                'id' => '245',
                'data_type_id' => '25',
                'field' => 'hold_ccp_dinar',
                'type' => 'text',
                'display_name' => 'Hold Ccp Dinar',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '11',
            ),
            169 => 
            array (
                'id' => '246',
                'data_type_id' => '25',
                'field' => 'hold_flexy_dinar',
                'type' => 'text',
                'display_name' => 'Hold Flexy Dinar',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '12',
            ),
            170 => 
            array (
                'id' => '247',
                'data_type_id' => '25',
                'field' => 'hold_paypal_usd',
                'type' => 'text',
                'display_name' => 'Hold Paypal Usd',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '13',
            ),
            171 => 
            array (
                'id' => '248',
                'data_type_id' => '25',
                'field' => 'hold_paypal_euro',
                'type' => 'text',
                'display_name' => 'Hold Paypal Euro',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '14',
            ),
            172 => 
            array (
                'id' => '249',
                'data_type_id' => '25',
                'field' => 'hold_paysera_usd',
                'type' => 'text',
                'display_name' => 'Hold Paysera Usd',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '15',
            ),
            173 => 
            array (
                'id' => '250',
                'data_type_id' => '25',
                'field' => 'hold_paysera_euro',
                'type' => 'text',
                'display_name' => 'Hold Paysera Euro',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '16',
            ),
            174 => 
            array (
                'id' => '251',
                'data_type_id' => '25',
                'field' => 'hold_mobilis_dinar',
                'type' => 'text',
                'display_name' => 'Hold Mobilis Dinar',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '17',
            ),
            175 => 
            array (
                'id' => '252',
                'data_type_id' => '25',
                'field' => 'hold_ooredoo_dinar',
                'type' => 'text',
                'display_name' => 'Hold Ooredoo Dinar',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '18',
            ),
            176 => 
            array (
                'id' => '253',
                'data_type_id' => '25',
                'field' => 'hold_djezzy_dinar',
                'type' => 'text',
                'display_name' => 'Hold Djezzy Dinar',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '19',
            ),
            177 => 
            array (
                'id' => '254',
                'data_type_id' => '25',
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => '1',
                'browse' => '1',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '20',
            ),
            178 => 
            array (
                'id' => '255',
                'data_type_id' => '25',
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => '1',
                'browse' => '0',
                'read' => '1',
                'edit' => '0',
                'add' => '0',
                'delete' => '0',
                'details' => '{}',
                'order' => '21',
            ),
        ));
        
        
    }
}