<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => '1',
                'menu_id' => '1',
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '1',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-06-30 18:59:02',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => '2',
                'menu_id' => '1',
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '10',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-05 21:38:35',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => '3',
                'menu_id' => '1',
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '9',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-05 21:38:35',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => '4',
                'menu_id' => '1',
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '8',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-05 21:38:35',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => '5',
                'menu_id' => '1',
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '14',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-05 21:38:31',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => '6',
                'menu_id' => '1',
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => '5',
                'order' => '1',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-01 15:39:26',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => '7',
                'menu_id' => '1',
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => '5',
                'order' => '2',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-01 15:39:26',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => '8',
                'menu_id' => '1',
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => '5',
                'order' => '3',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-01 15:39:26',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => '9',
                'menu_id' => '1',
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => '5',
                'order' => '4',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-01 15:39:26',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => '10',
                'menu_id' => '1',
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '15',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-05 21:38:31',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => '11',
                'menu_id' => '1',
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '13',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-05 21:38:31',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => '12',
                'menu_id' => '1',
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '11',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-05 21:38:35',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            12 => 
            array (
                'id' => '13',
                'menu_id' => '1',
                'title' => 'Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '12',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-05 21:38:35',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
            13 => 
            array (
                'id' => '14',
                'menu_id' => '1',
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => '5',
                'order' => '5',
                'created_at' => '2019-06-30 18:59:02',
                'updated_at' => '2019-07-01 15:39:26',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            14 => 
            array (
                'id' => '18',
                'menu_id' => '1',
                'title' => 'Services',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-truck',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '5',
                'created_at' => '2019-07-01 15:54:24',
                'updated_at' => '2019-07-05 21:38:41',
                'route' => 'voyager.services.index',
                'parameters' => NULL,
            ),
            15 => 
            array (
                'id' => '21',
                'menu_id' => '1',
                'title' => 'Currencies',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-diamond',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => '7',
                'created_at' => '2019-07-01 19:55:32',
                'updated_at' => '2019-07-05 21:38:41',
                'route' => 'voyager.currencies.index',
                'parameters' => 'null',
            ),
            16 => 
            array (
                'id' => '22',
                'menu_id' => '1',
                'title' => 'Payment Methods',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-paypal',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => '6',
                'created_at' => '2019-07-01 19:58:18',
                'updated_at' => '2019-07-05 21:38:41',
                'route' => 'voyager.payment-methods.index',
                'parameters' => 'null',
            ),
            17 => 
            array (
                'id' => '25',
                'menu_id' => '1',
                'title' => 'Payments',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-paypal',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => '2',
                'created_at' => '2019-07-02 16:05:59',
                'updated_at' => '2019-07-03 21:30:42',
                'route' => 'voyager.payments.index',
                'parameters' => 'null',
            ),
            18 => 
            array (
                'id' => '26',
                'menu_id' => '1',
                'title' => 'Deposits',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-paper-plane',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '3',
                'created_at' => '2019-07-03 21:44:48',
                'updated_at' => '2019-07-03 23:12:18',
                'route' => 'voyager.deposits.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => '27',
                'menu_id' => '1',
                'title' => 'Withdraws',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-dollar',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => '4',
                'created_at' => '2019-07-05 20:44:45',
                'updated_at' => '2019-07-05 21:40:03',
                'route' => 'voyager.withdraws.index',
                'parameters' => 'null',
            ),
            20 => 
            array (
                'id' => '28',
                'menu_id' => '2',
                'title' => 'financialServices',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => '1',
                'created_at' => '2019-07-07 22:35:40',
                'updated_at' => '2019-07-22 10:31:19',
                'route' => NULL,
                'parameters' => '',
            ),
            21 => 
            array (
                'id' => '33',
                'menu_id' => '2',
                'title' => 'payseraSold',
                'url' => 'services/financial-services/paysera-sold',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => '28',
                'order' => '1',
                'created_at' => '2019-07-07 22:48:46',
                'updated_at' => '2019-07-22 10:33:37',
                'route' => NULL,
                'parameters' => '',
            ),
            22 => 
            array (
                'id' => '34',
                'menu_id' => '2',
                'title' => 'Paysera sold',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => '32',
                'order' => '1',
                'created_at' => '2019-07-07 22:48:59',
                'updated_at' => '2019-07-07 22:49:04',
                'route' => NULL,
                'parameters' => '',
            ),
            23 => 
            array (
                'id' => '35',
                'menu_id' => '2',
                'title' => 'paypalSold',
                'url' => 'services/financial-services/paypal-sold',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => '28',
                'order' => '2',
                'created_at' => '2019-07-07 22:49:12',
                'updated_at' => '2019-07-22 10:33:59',
                'route' => NULL,
                'parameters' => '',
            ),
            24 => 
            array (
                'id' => '36',
                'menu_id' => '2',
                'title' => 'Paypal sold',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => '32',
                'order' => '2',
                'created_at' => '2019-07-07 22:49:33',
                'updated_at' => '2019-07-07 22:49:38',
                'route' => NULL,
                'parameters' => '',
            ),
            25 => 
            array (
                'id' => '37',
                'menu_id' => '2',
                'title' => 'khadamatSold',
                'url' => 'services/financial-services/khadamat-sold',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => '28',
                'order' => '3',
                'created_at' => '2019-07-07 23:59:25',
                'updated_at' => '2019-07-22 10:34:22',
                'route' => NULL,
                'parameters' => '',
            ),
            26 => 
            array (
                'id' => '39',
                'menu_id' => '1',
                'title' => 'Service Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '16',
                'created_at' => '2019-07-11 10:32:01',
                'updated_at' => '2019-07-11 10:32:01',
                'route' => 'voyager.service-categories.index',
                'parameters' => NULL,
            ),
            27 => 
            array (
                'id' => '40',
                'menu_id' => '1',
                'title' => 'Service Sub Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '17',
                'created_at' => '2019-07-11 10:45:23',
                'updated_at' => '2019-07-11 10:45:23',
                'route' => 'voyager.service-sub-categories.index',
                'parameters' => NULL,
            ),
            28 => 
            array (
                'id' => '41',
                'menu_id' => '1',
                'title' => 'Notifications',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '18',
                'created_at' => '2019-07-21 09:06:47',
                'updated_at' => '2019-07-21 09:06:47',
                'route' => 'voyager.notifications.index',
                'parameters' => NULL,
            ),
            29 => 
            array (
                'id' => '42',
                'menu_id' => '2',
                'title' => 'other',
                'url' => 'services/financial-services',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => '#000000',
                'parent_id' => '28',
                'order' => '4',
                'created_at' => '2019-07-22 10:42:55',
                'updated_at' => '2019-07-22 10:44:30',
                'route' => NULL,
                'parameters' => '',
            ),
            30 => 
            array (
                'id' => '43',
                'menu_id' => '1',
                'title' => 'Balances',
                'url' => '',
                'target' => '_self',
                'icon_class' => NULL,
                'color' => NULL,
                'parent_id' => NULL,
                'order' => '19',
                'created_at' => '2019-09-02 00:58:05',
                'updated_at' => '2019-09-02 00:58:05',
                'route' => 'voyager.balances.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}